package com.coffeetime.ui.theme

import androidx.compose.ui.graphics.Color

// Claro
val LightBackground = Color(0xFFFAF6F0)
val LightSurface = Color(0xFFFFFDF9)
val LightSurfaceContainer = Color(0xFFF3ECE2)
val LightSurfaceContainerHigh = Color(0xFFEBE1D4)
val LightOnSurface = Color(0xFF2A1D15)
val LightOnSurfaceVariant = Color(0xFF66564A)
val LightOutline = Color(0xFF8C7866)
val LightOutlineVariant = Color(0xFFE2D6C6)
val LightPrimary = Color(0xFF6B3F24)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFF2DCC8)
val LightOnPrimaryContainer = Color(0xFF3B2112)
val LightSecondary = Color(0xFFA8471D)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFFBE0D2)
val LightOnSecondaryContainer = Color(0xFF5A230B)
val LightTertiary = Color(0xFF2F6B5E)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFD3EBE3)
val LightOnTertiaryContainer = Color(0xFF0F3A31)
val LightError = Color(0xFFB3261E)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFF9DEDC)
val LightOnErrorContainer = Color(0xFF410E0B)
val LightWarning = Color(0xFF8A5A00)
val LightOnWarning = Color(0xFFFFFFFF)
val LightWarningContainer = Color(0xFFFBE7B5)
val LightOnWarningContainer = Color(0xFF3D2800)

// Oscuro
val DarkBackground = Color(0xFF17110D)
val DarkSurface = Color(0xFF211914)
val DarkSurfaceContainer = Color(0xFF2B221C)
val DarkSurfaceContainerHigh = Color(0xFF362B23)
val DarkOnSurface = Color(0xFFF2E8DD)
val DarkOnSurfaceVariant = Color(0xFFCBBBA9)
val DarkOutline = Color(0xFF9A8674)
val DarkOutlineVariant = Color(0xFF46392F)
val DarkPrimary = Color(0xFFE8B48C)
val DarkOnPrimary = Color(0xFF3A1F0E)
val DarkPrimaryContainer = Color(0xFF5A3520)
val DarkOnPrimaryContainer = Color(0xFFF7DCC6)
val DarkSecondary = Color(0xFFF29B70)
val DarkOnSecondary = Color(0xFF4A1A05)
val DarkSecondaryContainer = Color(0xFF6E2E12)
val DarkOnSecondaryContainer = Color(0xFFFFDCCB)
val DarkTertiary = Color(0xFF8FD1BF)
val DarkOnTertiary = Color(0xFF00382E)
val DarkTertiaryContainer = Color(0xFF1F4F45)
val DarkOnTertiaryContainer = Color(0xFFC4EDE1)
val DarkError = Color(0xFFF2B8B5)
val DarkOnError = Color(0xFF601410)
val DarkErrorContainer = Color(0xFF8C1D18)
val DarkOnErrorContainer = Color(0xFFF9DEDC)
val DarkWarning = Color(0xFFF2C35B)
val DarkOnWarning = Color(0xFF3D2800)
val DarkWarningContainer = Color(0xFF5C4000)
val DarkOnWarningContainer = Color(0xFFFBE7B5)
